### ISSUE TITLE
Xcode 14 compile error

### ISSUE THREAD

**Issue by shawna-mac2** [danielgindi/Charts#4867] opened 2022-07-14 17:44 UTC
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Installed Xcode 14 and ran on an iOS 16 simulator device 

## What did you expect to happen?

The library to build with out error

## What happened instead?

The library does not build. I saw other issues filed for Xcode 14 and they were different errors than what I noticed.  The following is the error and where it takes place: 

<img width="1194" alt="Screen Shot 2022-07-14 at 12 43 31 PM" src="https://user-images.githubusercontent.com/104022985/179048442-1f5c80ea-c8a0-4caf-9c56-44002e5a4cb2.png">

## Charts Environment

**Charts version/Branch/Commit Number:**
v4.0.3
**Xcode version:**
14
**Swift version:**
**Platform(s) running Charts:**
iOS 16 Simulator
**macOS version running Xcode:**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by shawna-mac2** [comment] 2022-07-14 17:46
I forgot to write, I'm running macOS 12.4

**Comment by mvn-thongnguyen-dn** [comment] 2022-07-20 07:06
Me either. I met the same compile error with my project with the same environment.

**Comment by richardpineo** [comment] 2022-07-25 21:09
Same error for me. This is a pressing issue because Xcode 14 beta is required to develop against iOS 16 beta.

**Comment by iDevPro** [comment] 2022-07-28 16:52
workaround:

```
let radarDataSets = radarData.compactMap { $0 as? RadarChartDataSetProtocol }
        for case let dataSet in radarDataSets where dataSet.isVisible
        {
            drawDataSet(context: context, dataSet: dataSet, mostEntries: mostEntries)
        }
```

**Comment by schnampcc** [comment] 2022-08-01 17:02
Duplicate of #4860 ?

**Comment by pmairoldi** [comment] 2022-09-13 02:36
closed by https://github.com/danielgindi/Charts/releases/tag/v4.1.0

**Closed by pmairoldi** 2022-09-13 02:36 UTC
