### ISSUE TITLE
Xcode 8.3 Compatible

### ISSUE THREAD

**Issue by alexruperez** [danielgindi/Charts#2125] opened 2017-02-01 07:39 UTC
In ChartDataEntryBase.swift binary operator '!==' cannot be applied to operands of type 'AnyObject?!' and 'AnyObject?'

**Comment by askielboe** [comment] 2017-02-01 11:55
duplicate of #2116

**Comment by petester42** [comment] 2017-02-02 02:03
closed by #2116

**Closed by petester42** 2017-02-02 02:03 UTC

**Comment by alexruperez** [comment] 2017-02-02 12:25
Sorry! 😓
