### ISSUE TITLE
The line chart enlarged is crash

### ISSUE THREAD

**Issue by laoSanDr** [danielgindi/Charts#2797] opened 2017-09-19 03:17 UTC
The new data will crash when the line graph is enlarged and then reassigned. If the assignment data is the same as before, it won't crash.

 charts crash code:
![ef792b4c-20cf-410e-b649-6e1bf160917a](https://user-images.githubusercontent.com/15378738/30574309-a1617aa8-9d2b-11e7-8676-7bcf3017b87b.png)

For help,thanks.

**Comment by liuxuan30** [comment] 2017-09-21 06:13
I need full steps to reproduce, especially prefer ChartDemo.

You should provide more info for a crash. Like input/crash log, not just this vague message

**Comment by PeterKovacs89** [comment] 2017-12-07 11:25
I'm experiencing a crash in the same function. Unfortunately, I can't reproduce it, but it's crashing in our beta-released version. I'm attaching the call-stack. The crash is not frequent but on the same dataset, it always happens. The crash happens in viewDidLoad, so the graph is not even appeared.

![call-stack](https://user-images.githubusercontent.com/22702305/33712727-bae5d022-db48-11e7-96c2-2a94f35a329b.png)

**Comment by liuxuan30** [comment] 2017-12-08 06:38
@PeterKovacs89  It may not be the same root cause for crashing. but for yours, a wild guess is your data sets is empty but try to calculate something.

If you are using crashlytics, you can add some log/var to print out the values when crashing.

**Comment by PeterKovacs89** [comment] 2017-12-08 10:45
I could reproduce the crash on an empty dataset, thank you for your help! <3

**Comment by liuxuan30** [comment] 2017-12-11 01:46
what's the cause then? A bug of ours or misusage? if latter, we can close this.

**Comment by PeterKovacs89** [comment] 2017-12-11 10:31
I know nothing about the original issue, my issue was a kind of misusage. Btw I think the framework should not crash when it receives empty data, so I think it should be fixed in any case.

**Comment by liuxuan30** [comment] 2017-12-12 01:24
We will try our best not to crash. But some crashes warns us what's wrong. Catching the crash and throw a log on your side will make us unaware of anything wrong.
Like in some cases, users pass an NaN or inf, we won't be able how to proceed and just crash to let you know.

**Closed by liuxuan30** 2017-12-12 01:24 UTC
Labels: missing info
