### ISSUE TITLE
rightAxis are rounded

### ISSUE THREAD

**Issue by orensha** [danielgindi/Charts#1238] opened 2016-07-10 10:35 UTC
i opened this issue berfore but you closed it even tough my problem wasnt solved.  so check this out.

again, i have two combined chart view's one under the other. when im adding the bottom chartview the values of the upper are rounded, it happens when the two graphs are not with the same interval value.

in this image you see the graphs with the same interval values, this one is fine
![screen shot 2016-07-10 at 1 25 31 pm](https://cloud.githubusercontent.com/assets/16323011/16713008/4af77734-46a2-11e6-81a0-0c7890c6ad27.png)

and in this one they arent
![screen shot 2016-07-10 at 1 25 51 pm](https://cloud.githubusercontent.com/assets/16323011/16713023/c2224ef6-46a2-11e6-8bde-431d4f5d82f5.png)

what can i do?  NSNumberFormatter donsnt seem to be solving it.

**Comment by liuxuan30** [comment] 2016-07-11 01:30
well as we discussed in your previous post, 
You have two charts:
1. one has a 0.756765 label for right axis;
2. after some ops, it has 1 rounded label for right axis. 

This is supposed to your code problem and we don't have any idea what's going on, and seems not a library bug.. unless you have proofs and code that we can reproduce.

I think it's about somewhere in your code that your value formatter is messed up, so you may start debugging from value formatter changes and value changes before and after what were you doing.

Last but not least, closing issues because we think it is answered, and no need to track. If you updated in the closed one, we(at least I) can still see, and reply or reopen if needed.

**Closed by liuxuan30** 2016-07-11 01:30 UTC
