### ISSUE TITLE
Bug with showing negative values and vertical zooming Horizontal Bar Chart

### ISSUE THREAD

**Issue by valery-demin** [danielgindi/Charts#1702] opened 2016-10-23 16:15 UTC
I am trying to use these Charts for showing negative values on Horizontal Bar Chart.
For horizontal zooming it works well but for vertical it has bug.
I have prepared GIF with this bug (from Demo project):
![horizontal bar chart](https://cloud.githubusercontent.com/assets/5167253/19627631/bd6bd400-9953-11e6-86ce-5550bbc14898.gif)

I have added `-i` instead of `i` in this string (https://github.com/danielgindi/Charts/blob/master/ChartsDemo/Classes/Demos/HorizontalBarChartViewController.m line 122):
`[yVals addObject:[[BarChartDataEntry alloc] initWithX:-i * spaceForBar y:val]];`

How can I avoid this behavior?

**Comment by liuxuan30** [comment] 2016-10-26 02:00
wait - after I add bug tag and want to fix, I can't reproduce it with latest release.
What's your library version? Can you try latest master? If you are dealing with 2.x, I am afraid we won't fix it.

**Comment by liuxuan30** [comment] 2016-10-26 02:36
@danielgindi I did a quick look, it is because the check
```swift
        for j in stride(from: 0, to: buffer.rects.count, by: 1)
        {
            let barRect = buffer.rects[j]
            
            if (!viewPortHandler.isInBoundsTop(barRect.origin.y + barRect.size.height))
            {
                break
            }
            
            if (!viewPortHandler.isInBoundsBottom(barRect.origin.y))
            {
                continue
            }
```
that break. However while testing it is more than I estimate the impact. It happens in  both bar chart and horizontal bar chart. So my commit does not fix it at all.

When trying to fix negative x values, it breaks positive x values; so I guess we can't simply fix it by changing around break/continue. Wanted to find an elegant but not yet. Maybe you can help here.

**Comment by liuxuan30** [comment] 2016-10-26 02:39
@valery-demin if you are hurry, one workaround for now is to use a formatter to add `-` prefix until we fix it

**Comment by liuxuan30** [comment] 2016-10-27 01:30
@danielgindi I have thought over it again, we had an implication that the x values should be ascending; people are not aware of this so weird thing happens. 
Ideally we should handle this but it seems it's a big change then to handle the x values' order.

**Comment by danielgindi** [comment] 2016-10-31 13:41
@liuxuan30 It must be ordered by definition, as we use the order to make quick searches through the values, and also optimize rendering loops by stopping when passed the last value to render.

@valery-demin you should use `addEntryOrdered` if you don't want to order your data by yourself...

**Closed by danielgindi** 2016-10-31 13:41 UTC
Labels: bug, ★★★

**Comment by liuxuan30** [comment] 2016-11-02 05:13
`addEntryOrdered()` never think about it.. so x values should be ordered as well now.
