### ISSUE TITLE
Demo in Swift?

### ISSUE THREAD

**Issue by nhantrivinh** [danielgindi/Charts#1548] opened 2016-09-24 09:10 UTC
Is there a demo in Swift?

**Comment by dhamukrish** [comment] 2016-09-24 13:05
You can start with this
https://www.appcoda.com/ios-charts-api-tutorial/

**Comment by nhantrivinh** [comment] 2016-09-24 14:12
Yes, I started with that and got what I needed. However, now that I have updated to the latest version for Xcode 8. My project is all messed up :(

**Comment by dhamukrish** [comment] 2016-09-24 15:34
But don't upgarde to Sierra till 10.12.1 released

Regards
Dhamu
http://digidhamu.com

**Comment by thexande** [comment] 2016-09-24 19:42
Anybody know when the version supporting swift 3/ Xcode 8 is going to be distributed with pods?

**Comment by petester42** [comment] 2016-09-24 20:01
When version 3.0 is finished. You can use it now by pointing your podfile to the master branch.

**Comment by thexande** [comment] 2016-09-24 20:20
@petester42 Thanks for the tip. 

I have it in the podfile like so: 

```ruby
    pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'master'
```

Install goes great, i get version 3.0: 

![screen shot 2016-09-24 at 2 12 05 pm](https://cloud.githubusercontent.com/assets/7704414/18810979/69105f24-8261-11e6-9f6a-87a6af53c892.png)


The problem is when I build, Im getting a Dependency Analysis Error:

``` 
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
```

As well as the linker error and the script invocation error:

```
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
/Users/alexandermurphy/Library/Developer/Xcode/DerivedData/sparkpoll-cwcuoemcojbuazfttwipycigkggz/Build/Products/Debug-iphonesimulator/sparkpoll.app/Frameworks/Charts.framework: No such file or directory

```
I think the no file or dir error is caused by the pod not being built because of the legacy swift syntax, but isn't the version 3.0 supposed to support Xcode8 / swift3 combo?

Thanks again!

**Comment by petester42** [comment] 2016-09-24 20:24
You might need to use cocoapods version 1.1.0 for better Xcode 8 support. Try installing 1.1.0.rc.2 and make sure your project has the correct setting for swift 3 before running pod install. 

Or you can add a post install hook in your podfile to update the swift version. A quick search on Google will get you the hook.

**Comment by thexande** [comment] 2016-09-24 20:39
@petester42 

Your instincts were correct. This was the process to get a successful build using Xcode8 / swift 3 combo:

 ### Step 1: install latest version of cocoapods
``` gem install cocoapods -v 1.1.0.rc.2 ```
### Step 2: set podfile entry
```ruby     pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'master' ```
### Step 3: set post install hook for compiler verison
```  ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

### Step 4: Build and Rejoice 
![screen shot 2016-09-24 at 2 39 25 pm](https://cloud.githubusercontent.com/assets/7704414/18811138/bbef82d0-8264-11e6-9d97-e8fe7c630168.png)

**Comment by thexande** [comment] 2016-09-24 20:40
I am working on putting together a basic demo for this configuration and some basic charts.

**Comment by thexande** [comment] 2016-09-24 22:07
@petester42 Trying to write a demo to close this issue, would you mind taking a quick peek at #1554 ? You might know the problem right away.

**Comment by liuxuan30** [comment] 2016-09-26 01:17
OS X is swift demo. For other issues it's off topic so I am closing.

**Closed by liuxuan30** 2016-09-26 01:17 UTC

**Comment by lazar108** [comment] 2017-03-01 02:17
@thexande thank god I found this! it helped a lot, using this project was a huge problem

**Comment by User2004** [comment] 2019-01-26 06:20
https://webappcodes.com/category/ios

here is a demo in swift
