### ISSUE TITLE
Horizontally flipped x-axis

### ISSUE THREAD

**Issue by cepages** [danielgindi/Charts#738] opened 2016-02-04 15:47 UTC
Hi, my app is in iOS9 and it's in English and Arabic. I'm using the Chart ```LineChartView```

Whit the new methods from UIKit for International User Interfaces is pretty easy to mirror all the elements, but I can't mirror the graph.

Currently with my phone in Arabic and with the right localization all views are mirrored except the Chart.

Also because ```LineChartView``` is a view I tried:
```    [[LineChartView appearance] setSemanticContentAttribute:UISemanticContentAttributeForceRightToLeft];```

But it didn't work, is there any way to do it? It's because the library doesn't support this?

Thanks.

**Comment by danielgindi** [comment] 2016-02-04 15:53
The library does not support this fully.

There are things you can do: For example you can tell the legend to be RTL.

Note that in most cases when dealing with numbers the correct thing to do is have the axis on the left, as numbers go from left to right.
When dealing with text - then it depends on your language...

**Comment by cepages** [comment] 2016-02-04 16:33
Thanks @danielgindi 

About the number I think that if you have the number in Arabic this would follow the direction right to left. So I guess the axis would be needed inverted, is possible to do this manually?

**Comment by danielgindi** [comment] 2016-02-23 21:17
I guess there would be cases where an inverted axis is required.

It is not supported right now - but in about 10 minutes I think you can get it working. Look at the code for the horizontal bar chart axis renderer - it flips all the axes on the side.
You just need ltr-rtl flipping - which should be much easier :-)

**Comment by danielgindi** [comment] 2016-08-10 20:13
This seems like a duplicate of #253. See the updates there...

**Closed by danielgindi** 2016-08-10 20:13 UTC
Labels: feature

**Comment by Dev-Khaled** [comment] 2022-02-15 13:04
Just revert your dataset, and enable right axes instead of left axes, this should do the trick
