### ISSUE TITLE
Bar chart floating y position

### ISSUE THREAD

**Issue by nspavlo** [danielgindi/Charts#947] opened 2016-04-13 14:52 UTC
Hello.
I'm using BarChartView with following configuration:
```
- (BarChartView *)chartView
{
    if (_chartView) {
        return _chartView;
    }
    _chartView = [[BarChartView alloc] initForAutoLayout];
    _chartView.minOffset = 1.0f;
    _chartView.descriptionText = @"";
    _chartView.noDataTextDescription = @"";
    _chartView.maxVisibleValueCount = 20;
    _chartView.drawBarShadowEnabled = NO;
    _chartView.pinchZoomEnabled = NO;
    _chartView.drawGridBackgroundEnabled = NO;
    _chartView.xAxis.enabled = NO;
    _chartView.leftAxis.enabled = NO;
    _chartView.rightAxis.enabled = NO;
    _chartView.legend.enabled = NO;
    _chartView.userInteractionEnabled = NO;
    _chartView.noDataText = @"";    
    return _chartView;
}
```

BarChartData is updated every second. After a while chart y position is changing. Smth. like +/- 8pt.
Is it configurable? 
Thanks in advance.

**Comment by liuxuan30** [comment] 2016-04-14 02:38
Not sure what you want to config. x axis is index based, so depends on how many bars you have, the x value position is calculated then.

**Comment by nspavlo** [comment] 2016-04-14 10:51
Always same number of items (bars). Only values is changing.

**Comment by liuxuan30** [comment] 2016-04-14 11:17
then update your data sets

**Comment by nspavlo** [comment] 2016-04-14 11:40
Thanks, but I think we're not on the same page here. I will create example project. :)

**Comment by liuxuan30** [comment] 2016-04-14 11:43
maybe screenshots and explaination, demo project is too heavy

**Comment by nspavlo** [comment] 2016-04-14 12:11
Initial state: 
![img_1906](https://cloud.githubusercontent.com/assets/5214134/14527490/14ffb4a4-0253-11e6-92dd-8a83992bded1.PNG)

After a while: 
![img_1905](https://cloud.githubusercontent.com/assets/5214134/14527492/1f2cfcd4-0253-11e6-809f-ead96cd7167e.PNG)

**Comment by jleach** [comment] 2016-04-14 22:27
I have the same problem. If I have 10 xAxes values, 9 of which are 0 (no bar) and the 10th value is say 20 (anything > 0) then the single bar floats about 10px above the x-axis. If on the other hand, I have 10 xAxis values, all of which are > 0 then they all sit right on the x-axis. 

You can see this in the image above. In the initial state, the bars are floating ~10 px above the x-axis. However, in the "After a while" graph you can see they're much closer to the x-axis. This happens when some of the bars have a 0 value.

**Comment by liuxuan30** [comment] 2016-04-15 01:19
could just print out the y axis values, so we know the y axis range? Also, which version are you using? 
I doubt it's related to recent change about deprecating startAtZeroEnabled and moving to axisMinValue.
Please check.
forcing axisMinValue = 0 will make the y axis always started from 0.

**Comment by nspavlo** [comment] 2016-04-15 10:22
Initial:
![img_1911](https://cloud.githubusercontent.com/assets/5214134/14558799/1560b744-030d-11e6-9cf9-e38347d26567.PNG)

After a while:
![img_1914](https://cloud.githubusercontent.com/assets/5214134/14558806/1e629b8c-030d-11e6-9399-63780549bec0.PNG)

**Comment by jleach** [comment] 2016-04-15 18:09
For me I have 24 values; index 0 = 71, the rest of zero. Also, I have `rightAxis.startAtZeroEnabled = true` I walked through the render bar method and it looks like it should be drawing ok. Maybe its the axes that is being draw too low?

![fullsizerender](https://cloud.githubusercontent.com/assets/390891/14570697/7ca1404e-02fa-11e6-9970-c1a02e9e5754.jpg)

**Comment by danielgindi** [comment] 2016-04-17 17:01
If I understand you correctly, your Y values range is changing. When the max value is getting bigger, the other bars are getting smaller relatively.
You can control the minimum/maximum Y axis values, using `axisMinValue`.
Or you can use `setVisibleYRangeMaximum` to limit the Y scale and force the user to pan...

**Comment by liuxuan30** [comment] 2016-04-18 02:36
@jleach seems your issue is different? I tried your 71 and 23 zeroes with ChartsDemo, it's fine. I think you got something wrong with your code, or you modified something. The typical work flow is first configure the chart properties, and then setup the data. Make sure chartView.data = yourData is the last line; or you call notifyDataSetChanged() everytime you changed something about axis ranges.

**Comment by jleach** [comment] 2016-04-19 19:26
@liuxuan30 I tried moving the chartView.data = to the be the last line and tried calling notifyDataSetChated() - no luck. Here is my method: 
https://gist.github.com/jleach/ef831910e5dd16a785361533df73113e

I'll go back and see if I'm messing with the layout or something. The only thing I can think of is that I'm embedding the chart in a UIView. Maybe a constraint is causing me grief?

**Comment by liuxuan30** [comment] 2016-04-20 01:35
@jleach constraints should impact the whole chart view, not just axis or a bar right? unless you separate them.. Anyway, please try ChartsDemo to see if you can reproduce.

**Comment by danielgindi** [comment] 2016-05-15 06:53
You have not responded to my reply. Have you checked it out?
Also there are dedicated `addEntry`/`removeEntry` functions to add/remove entry without calling `notifyDataSetChanged`.

**Closed by danielgindi** 2016-05-15 06:53 UTC
