### ISSUE TITLE
Bars in BarChartView become invisible if the x-value in DataEntry is of certain values

### ISSUE THREAD

**Issue by alanlo-hkej** [danielgindi/Charts#1716] opened 2016-10-26 04:22 UTC
When the input x-values for the data entries of bar chart are set to certain values, the bars in the chart will become invisible, while the value labels for corresponding bar are showing. I've made a sample project reproducing this issue and hope to see if I am missing something or is there something wrong.

Sample project:
[ChartTest.zip](https://github.com/danielgindi/Charts/files/552333/ChartTest.zip)

In the sample project, commenting one of the lines initiating xVal in the following method:

```
- (void)setChartData {
    NSMutableArray *arr_tempEntry = [NSMutableArray array];
    for (int i = 0 ; i < 28 ; i++) {

        // comment out one of the following lines for xVal
        double xVal = 86400.0 * (i + 1);
        //double xVal = i + 1;
        NSInteger yVal = arc4random_uniform(15000);

        BarChartDataEntry *dataEntry = [[BarChartDataEntry alloc] initWithX:xVal y:yVal];
        [arr_tempEntry addObject:dataEntry];
        xVal++;
    }

    BarChartDataSet *dataSet = nil;
    if (self.barChartView.data.dataSetCount > 0) {
        dataSet = (BarChartDataSet *)[self.barChartView.data.dataSets firstObject];
        dataSet.values = arr_tempEntry;
        [self.barChartView.data notifyDataChanged];
        [self.barChartView notifyDataSetChanged];
    } else {
        dataSet = [[BarChartDataSet alloc] initWithValues:arr_tempEntry];
        [dataSet setColor:[UIColor colorWithRed:113/255.f green:200/255.f blue:177/255.f alpha:1.f]];
        //dataSet.drawValuesEnabled = FALSE;

        NSMutableArray *dataSets = [NSMutableArray array];
        [dataSets addObject:dataSet];

        BarChartData *data = [[BarChartData alloc] initWithDataSet:dataSet];
        data.barWidth = 0.8f;
        self.barChartView.data = data;
    }
}
```

If the line `double xVal = i + 1;` is used, the bar chart has no problem at all, which gives the following result:
![simulator screen shot 26 oct 2016 12 20 58 pm](https://cloud.githubusercontent.com/assets/17443758/19713204/ad4db690-9b76-11e6-8426-a03a01814a86.png)
However, if the line `double xVal = 86400.0 * (i + 1);` is used, the bar chart will give the following result:
![simulator screen shot 26 oct 2016 12 15 30 pm](https://cloud.githubusercontent.com/assets/17443758/19713130/0a638a54-9b76-11e6-9c66-53186a90de38.png)
The x-values are setting these large as I am using it to plot chart showing data with respect to date, which those are in fact NSTimeInterval. I am kind of stuck here and have been trying some other settings like setting granularity to different values like 0.0, 1.0 as well as 86400.0, adjusting bar width, etc, but they don't work at all. 

Thanks for any help!

**Comment by avitus** [comment] 2016-10-31 21:17
Yes, if I divide the timeInterval by 10,000 (which obviously gives the wrong date) then the bars in the graph are visible:

`let timeIntervalForDate: TimeInterval = i.entryDate.timeIntervalSince1970 / 10000`

Otherwise, they are invisible.

**Comment by JeremyChiang** [comment] 2016-11-01 20:56
Digging into the source code, I think the issue is in the `computeAxisValues(min:max:)` function in **AxisRendererBase.swift**

I haven't had the time to figure everything out yet, but it looks like the code between line 176 and 194 is rounding up my time intervals for the x-axis, and therefore setting an array of incorrect doubles for the x-axis' `entries` property. I thought the `entries` array in my x-axis is supposed to match the x values I've passed in when I called `addEntry`:

```
chartDataSet.addEntry(
    BarChartDataEntry(x: timeInterval, y: value)
)
````

````
// Ensure stops contains at least n elements.
axis.entries.removeAll(keepingCapacity: true)
axis.entries.reserveCapacity(labelCount)
            
var f = first
var i = 0
while i < n
{
    if f == 0.0
    {
        // Fix for IEEE negative zero case (Where value == -0.0, and 0.0 == -0.0)
        f = 0.0
    }
                
    axis.entries.append(Double(f))
                
    f += interval
    i += 1
}
````

**Comment by liuxuan30** [comment] 2016-11-02 05:25
No, `axis.entries` is the calculated x value labels appears on the x axis. It won't match your data entry.

**Comment by liuxuan30** [comment] 2016-11-03 02:14
I think this is a dup to https://github.com/danielgindi/Charts/issues/1742. closing.

**Closed by liuxuan30** 2016-11-03 02:14 UTC
Labels: bug

**Comment by kabouzeid** [comment] 2018-09-09 16:36
I could solve it by sorting the values from smallest to largest x first
