### ISSUE TITLE
LineChart Axis Inset?

### ISSUE THREAD

**Issue by msanders** [danielgindi/Charts#46] opened 2015-04-23 22:44 UTC
Hi, thanks for the great library! Is it possible to add an inner padding to x axes as shown in the picture below?

![graph padding](https://cloud.githubusercontent.com/assets/54970/7309042/131fe0b6-e9cf-11e4-9607-4018a6b66e7c.png)

I.e., both the first and last points and xAxis labels are inset by ~15px. Would be super useful. Thanks!

**Comment by danielgindi** [comment] 2015-05-02 20:52
@PhilJay what do you think? do we have an easy way of "skipping" x-indexes?

**Comment by PhilJay** [comment] 2015-05-03 08:13
Well an easy workaround could be to use "" as the first x value and then insert the first entry at x index 1

**Comment by danielgindi** [comment] 2015-05-03 08:22
@msanders did that solve your problem?

**Comment by msanders** [comment] 2015-05-04 18:36
@danielgindi No, that insets it much more than I wanted. Is it not possible to add an inset property just for layout?

**Comment by danielgindi** [comment] 2015-05-04 18:37
Not right now - we'll have to look into it

**Comment by BurhanMughal** [comment] 2015-05-13 11:31
Any News about above mentioned issue ?

**Comment by danielgindi** [comment] 2015-05-13 11:33
@BurhanMughal Please, you are creating too much noise in the system. If there were new, you would have known. You are welcome to try to implement whatever feature is missing, or wait until someone else or I make it.

**Comment by BurhanMughal** [comment] 2015-05-13 11:59
Sorry Daniel if you feel bad. But i was just looking to get informed that the issue is still in process because you closed this issue.

**Comment by msanders** [comment] 2015-05-13 19:08
@danielgindi Any thoughts as to how we could go about implementing this? Would it just be an update to `ChartXAxisRenderer`?

**Comment by danielgindi** [comment] 2015-05-13 19:21
I closed it earlier when there was no response to the suggestions

**Comment by danielgindi** [comment] 2015-05-13 19:23
Well it wouldn't be just about the XAxisRenderer as the other renders (the
chart renderers) would need the spacing also.
So I guess it would be in the ViewPort, but I did not have the time to look
into it yet, as we have other things on our plate :)

‏בתאריך יום רביעי, 13 במאי 2015, Daniel Cohen Gindi <danielgindi@gmail.com>
כתב:

> I closed it earlier when there was no response to the suggestions
>
>
>

**Comment by SvenMuc** [comment] 2015-08-24 21:12
Tried to analyze the ChartViewPortHandler.swift file in order to set the inset. So far without any success. It's hard to understand the code.

I tried to modify the ```_contentRect```, but this changes the size of the whole diagram. As a next step I will try to test different effects by changing the affine transformation.

Does someone can give me a short hint?

**Comment by liuxuan30** [comment] 2015-08-26 01:56
speaking of view port handler, you need to think about the transformers. ios-charts need the transformer to calculate the postions. will adding slight offset in transformer help?

**Comment by odedharth** [comment] 2016-04-19 12:49
tried @PhilJay suggestion but it's problematic when you have few entries... 
![photo 19-04-2016 3 38 25 pm](https://cloud.githubusercontent.com/assets/624023/14639621/3dbfc8a6-0646-11e6-8fb4-29410c954f3a.png)

**Comment by liuxuan30** [comment] 2016-04-20 01:23
did anyone tried to change chartXMin so it will have slight offset at the beggining? I remember I tried once

**Comment by danielgindi** [comment] 2016-08-10 20:01
Implemented in Charts 3.0 (v3 branch) (Use `axisMinValue`/`axisMaxValue`)

**Closed by danielgindi** 2016-08-10 20:01 UTC
Labels: feature

**Comment by liuxuan30** [comment] 2016-08-12 00:17
does it hold a property for that?

**Comment by pouriaalmassi** [comment] 2016-09-06 22:05
@odedharth  Could you please share your approach to this? I'm having some trouble accomplishing the same result.

**Comment by DevangiDesai** [comment] 2017-03-30 06:03
@danielgindi Hi, I wanted to know that is this issue fixed? I am facing same problem. I want padding left and right on xAxis.

**Comment by DevangiDesai** [comment] 2017-03-30 06:18
Found solution for spacing on xAxis 
        chartView.xAxis.spaceMin = 0.5
        chartView.xAxis.spaceMax = 0.5

**Comment by jtbh89** [comment] 2017-06-17 20:23
spaceMin / spaceMax didn't work for me but adjusting axisMinValue / axisMaxValue slightly did.

**Comment by 29satnam** [comment] 2018-05-09 08:26
@DevangiDesai solution does work if you want to add **padding on xAxis at right and left**.

`self.chartView.xAxis.spaceMin = 10;
self.chartView.xAxis.spaceMax = 2;`

Here's a preview for future viewers: 

![screen shot 2018-05-09 at 1 50 45 pm](https://user-images.githubusercontent.com/3638092/39804033-9b2d7594-5390-11e8-817d-568e75983b0d.png)

**Comment by fmessina** [comment] 2019-08-14 13:46
I've been trying to achieve this on a `LineChartView` but cannot get it to work properly.
From the comments above I'm not sure to understand how to do it.

Has someone ever found a way to achieve it?

**Comment by iraklivasha** [comment] 2019-08-16 07:37
Hi Guys,

Can someone point the exact configuration for LineChartView so it displays paddings from left and right ? @DevangiDesai  I tried code below too,  but with no luck.  Is there any chance that some other configuration is overlapping this settings ?
```
chartView.xAxis.spaceMin = 0.5
chartView.xAxis.spaceMax = 0.5
```
<img width="728" alt="Screen Shot 2019-08-16 at 11 31 28 AM" src="https://user-images.githubusercontent.com/4551834/63151142-ddd5c300-c019-11e9-8fc6-bacf7bfc30c2.png">

**Comment by elliotcz97** [comment] 2020-08-05 17:45
Today i faced the same problem as you guys. The methods to use are: 
`chartView.xAxis.spaceMin = 0.5
chartView.xAxis.spaceMax = 0.5`

If you want it to work you have to set these properties before you set the data of the chart (at least i got it this way to work)

So for my project i did it this way: 
`let data = LineChartData(dataSet: dataSet)
            chartView.xAxis.spaceMin = 0.2
            chartView.xAxis.spaceMax = 0.2
            
            chartView.data = data`

I hope this helps someone in the future. Great library btw, i love it!

**Comment by seriyvolk83** [comment] 2020-08-20 09:24
```
chartView.minOffset = 0
```

**Comment by cameronehrlich** [comment] 2021-04-13 01:03
> Not the solution, but will help anyone who searches for how to remove the paddings:
> 
> ```
> chartView.xAxis.avoidFirstLastClippingEnabled = true
> chartView.minOffset = 0
> ```

Thank you @seriyvolk83, this solved the problem I was having!
