### ISSUE TITLE
Xcode - 8.0, Working Fine in Xcode 7.3  -up to iOS(9.3) Crash in Xcode 8 - iOS 10  

### ISSUE THREAD

**Issue by KushThakkar** [danielgindi/Charts#1624] opened 2016-10-08 06:47 UTC
Hello,
I am using BarChart and its working fine upto 7.3 and Its not support in iOS 10 and App go to Crash.
Now I am run my Project in XCode 8. Now Its going to Crash.

I am using Below code. Please Review It. Please give Suggestion steps for Solve this.

cell.viewBarChart.data = self.setChartBarGroupDataSet(arrAgeGrop, values: arrPositive, values2:arrNegative, sortIndex: 1)

For Set The Data -

func setChartBarGroupDataSet(dataPoints: [String], values: [Double], values2: [Double],sortIndex:Int)-> BarChartData {
        
        var dataEntries: [BarChartDataEntry] = []
        var dataEntries2: [BarChartDataEntry] = []
        for i in 0..<dataPoints.count {
            let dataEntry = BarChartDataEntry(value: values[i], xIndex: i)
            dataEntries.append(dataEntry)
        }
        for i in 0..<dataPoints.count {
            let dataEntry = BarChartDataEntry(value: values2[i], xIndex: i)
            dataEntries2.append(dataEntry)
        }
        let chartDataSet = BarChartDataSet(yVals: dataEntries, label: "Pos")
        let chartDataSet2 = BarChartDataSet(yVals: dataEntries2, label: "Neg")
        chartDataSet2.colors =  [UIColor.redColor()]
        chartDataSet.colors =  [UIColor.greenColor()]
        let dataSets: [BarChartDataSet] = [chartDataSet,chartDataSet2]
        let data = BarChartData(xVals: dataPoints, dataSets: dataSets)
        return data
    }

**Comment by ZetrixWeb-iOS** [comment] 2016-10-08 06:52
+1 same issue

**Comment by ZetrixWeb-iOS** [comment] 2016-10-08 07:18
![screen shot 2016-10-08 at 12 46 50 pm](https://cloud.githubusercontent.com/assets/7457258/19211244/6245d364-8d55-11e6-8da1-1da6640d11c9.png)
Please check screenshot

**Comment by liuxuan30** [comment] 2016-10-10 06:51
I need the crash log to identify.
But have you update your library? What version or branch of the library you are using?

**Comment by danielgindi** [comment] 2016-10-10 14:42
Some race conditions in Charts 3.0 have been fixed in the last few days. So you might want to pull `master`

**Comment by petester42** [comment] 2016-10-12 22:42
For the error you have setup your interface builder stuff incorrectly. You need to specify the module probably.

**Comment by madhikarma** [comment] 2016-10-17 20:29
Hi @KushThakkar Did you manage to resolve your issue here by using the latest code from master? Have you tried what was suggested above regarding Interface Builder or tried using code instead? Let us know if you are still have trouble here

**Comment by danielgindi** [comment] 2016-10-18 16:02
I actually think that the problem is correct Interface Builder references to the class names, as @petester42 suggested, or a Clean & Build. 

Since no response has been posted in 10 days, I'm going to assume he figured it out already...

**Closed by danielgindi** 2016-10-18 16:02 UTC
