### ISSUE TITLE
Not able to compile code on Xcode 14 Beta 3

### ISSUE THREAD

**Issue by NiksTambat** [danielgindi/Charts#4873] opened 2022-07-26 09:44 UTC
## What did you do?

ℹ I have Updated pods after Xcode and macOS update 

## What did you expect to happen?

ℹ It should compile the code on Xcode 14 Beta 3 and with iOS 16 

## What happened instead?

ℹ I am facing following errors in library -

1. Type 'ChartDataSet' does not conform to protocol 'RangeReplaceableCollection'
2. Unavailable instance method 'replaceSubrange(_:with:)' was used to satisfy a requirement of protocol 'RangeReplaceableCollection'
3. Referencing instance method 'makeIterator()' on 'Collection' requires the types 'IndexingIterator<ChartData>' and 'IndexingIterator<RadarChartData>' be equivalent  

## Charts Environment

**Charts version/Branch/Commit Number:** 4.0.3
**Xcode version:** 14.0 Beta 3
**Swift version:** 5.0
**Platform(s) running Charts:** -
**macOS version running Xcode:** Ventura 13.0 Beta

**Comment by tariqsclubwise** [comment] 2022-07-26 11:27
Facing same issue.

**Comment by AndrewBennet** [comment] 2022-07-26 21:07
Also hit this issue. I wonder whether this is related to this Swift bug? https://github.com/apple/swift/issues/60085

**Comment by billThePill** [comment] 2022-07-28 00:02
It occurs with Beta 4 released today as well...
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/16886642/181392518-49d558de-2d14-486d-b6d4-7cdf8f3f23f8.png">

**Comment by iDevPro** [comment] 2022-07-28 17:12
workaround or patch:
append it to `extension ChartDataSet: RangeReplaceableCollection`

```
public func replaceSubrange<C>(_ subrange: Swift.Range<Int>, with newElements: C) where C : Collection, ChartDataEntry == C.Element {
        entries.replaceSubrange(subrange, with: newElements)
        notifyDataSetChanged()
    }
```

have older issue after ))))))
![charts](https://user-images.githubusercontent.com/1888230/181597570-8563d189-a9d8-4bba-a2f5-dbc2cf37a3cb.png)

**Comment by brendand** [comment] 2022-07-29 03:44
Is there a solution to the EaseOutBack error?

**Comment by NiksTambat** [comment] 2022-07-29 06:02
@iDevPro 

Thanks for the solution. It Works for me. 

But now I am facing another issue : 

**Referencing instance method 'makeIterator()' on 'Collection' requires the types 'IndexingIterator<ChartData>' and 'IndexingIterator<RadarChartData>' be equivalent**

![Screenshot 2022-07-29 at 11 19 23 AM](https://user-images.githubusercontent.com/110026069/181692926-68450e26-7dce-43d1-b277-49e10c613d08.png)

Please help me if anyone has any solution for this

**Charts Environment: -**

Charts version/Branch/Commit Number: 4.0.3
Xcode version: 14.0 Beta 3
Swift version: 5.0
Platform(s) running Charts: -
macOS version running Xcode: Ventura 13.0 Beta

**Comment by schnampcc** [comment] 2022-08-01 17:01
Duplicate of #4860 ?

**Comment by Nikojoel** [comment] 2022-08-20 13:44
Facing the same issue

**Comment by josipbernat** [comment] 2022-08-23 11:01
The same issue here.

**Comment by doshirj** [comment] 2022-08-23 20:14
Casting the data object to ChartData seems to resolve the "makeIterator" compile errors. I haven't confirmed that the code runs correctly.

`for case let set as RadarChartDataSetProtocol in radarData as ChartData where set.isVisible`

**Comment by alperenarc** [comment] 2022-09-05 11:39
The solutions to this problem have been merged into the master branch. However, no new version has been released. So you can use it like

pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'master'
@josipbernat @doshirj @Nikojoel

**Comment by premkumarmsc** [comment] 2022-09-08 10:41
> The solutions to this problem have been merged into the master branch. However, no new version has been released. So you can use it like
> 
> pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'master' @josipbernat @doshirj @Nikojoel

Great

**Comment by nikitap1298** [comment] 2022-09-12 20:50
September 12, Xcode 14.0
How to fix this?
![Screenshot 2022-09-12 at 23 49 35](https://user-images.githubusercontent.com/101060848/189756033-35ceb78c-3b4b-4688-bb5b-6d9d9b690419.png)

**Comment by cameronehrlich** [comment] 2022-09-12 21:05
Can we cut a new release now?

**Comment by nikitap1298** [comment] 2022-09-12 21:20
> 
I've fixed this
https://github.com/danielgindi/Charts/pull/4861

**Comment by pmairoldi** [comment] 2022-09-13 02:35
closed by https://github.com/danielgindi/Charts/releases/tag/v4.1.0

**Closed by pmairoldi** 2022-09-13 02:35 UTC

**Comment by usama4792** [comment] 2022-09-15 09:32
> workaround or patch: append it to `extension ChartDataSet: RangeReplaceableCollection`
> 
> ```
> public func replaceSubrange<C>(_ subrange: Swift.Range<Int>, with newElements: C) where C : Collection, ChartDataEntry == C.Element {
>         entries.replaceSubrange(subrange, with: newElements)
>         notifyDataSetChanged()
>     }
> ```
> 
> have older issue after )))))) ![charts](https://user-images.githubusercontent.com/1888230/181597570-8563d189-a9d8-4bba-a2f5-dbc2cf37a3cb.png) which also can fix, but move from CocoaPods to SPM Package :)

thanks so much bro for your help

**Comment by rupalchawla** [comment] 2022-09-17 18:43
This was fixed in Charts pod 4.1.0

**Comment by phamhieu1412** [comment] 2022-09-20 05:53
> This was fixed in Charts pod 4.1.0

how to update Charts pod to 4.1.0. I try "pod update Charts" but not oke, current version is 3.6.0. i try change in podfile.lock but show error "react-native-charts-wrapper (from `../node_modules/react-native-charts-wrapper`) was resolved to 0.5.9, which depends on
      Charts (= 3.6.0)"

**Comment by rupalchawla** [comment] 2022-09-20 06:45
> Check the platform version in your podfile, update it to 15 and then try pod update again 
`platform :ios, '15.0'`



> > This was fixed in Charts pod 4.1.0
> 
> how to update Charts pod to 4.1.0. I try "pod update Charts" but not oke, current version is 3.6.0. i try change in podfile.lock but show error "react-native-charts-wrapper (from `../node_modules/react-native-charts-wrapper`) was resolved to 0.5.9, which depends on Charts (= 3.6.0)"

**Comment by phamhieu1412** [comment] 2022-09-20 07:15
> > Check the platform version in your podfile, update it to 15 and then try pod update again
> > `platform :ios, '15.0'`
> 
> > > This was fixed in Charts pod 4.1.0
> > 
> > 
> > how to update Charts pod to 4.1.0. I try "pod update Charts" but not oke, current version is 3.6.0. i try change in podfile.lock but show error "react-native-charts-wrapper (from `../node_modules/react-native-charts-wrapper`) was resolved to 0.5.9, which depends on Charts (= 3.6.0)"

tks you, but not ok, then pod update, charts having version is 3.6.0 and error above :(((, another solution??.  i usse react native 0.63.2

**Comment by rupalchawla** [comment] 2022-09-20 07:47
The solution I provided works for iOS native app, I don't know if same applies to react native

**Comment by tejasNix** [comment] 2022-09-20 19:50
> > This was fixed in Charts pod 4.1.0
> 
> how to update Charts pod to 4.1.0. I try "pod update Charts" but not oke, current version is 3.6.0. i try change in podfile.lock but show error "react-native-charts-wrapper (from `../node_modules/react-native-charts-wrapper`) was resolved to 0.5.9, which depends on Charts (= 3.6.0)"

https://github.com/wuxudong/react-native-charts-wrapper/issues/894

**Comment by julien-tamade** [comment] 2022-09-27 23:01
> ```
> pod 'Charts', '~> 4.1.0'
> ```
> 
> It fixes my issues but it creates few more for my project, like
> 
> * Cannot find type 'IAxisValueFormatter' in scope
> * Cannot use optional chaining on non-optional value of type 'Description'
> 
> Replace IAxisValueFormatter with AxisValueFormatter Removed ? or just follow Xcode suggestion

I'm having this same issue

**Comment by saqlainbhatti** [comment] 2022-11-03 11:05
Well solution available on the following link, Worked for me

https://stackoverflow.com/questions/74010925/charts-not-compile-on-xcode-14

**Comment by Haibo-Zhou** [comment] 2022-12-15 05:40
I meet the same issue, update to 4.1.0 create a few more errors.
